Improve instruction on how to run the sample
go-authboss/authboss-sample pull request #14
Opened 2017-02-09 00:17 UTC by manhg

* Add env variable to configure example app.
* Link to test Google OAuth

2017-03-15 17:20 UTC, edwinthinks requested changes
I left a minor change suggestion.

Currently the master branch has a login user hardcoded and registering new users do not work due to hardcoded password input. I'd specifically say that in the README until it has been modified.

Thanks for improving the documentation. I was having a little difficulty in understanding it on first look. 👍

2017-03-15 17:20 UTC, cintosyntax commented on README.md
> +go get github.com/go-authboss/authboss
I think this should be `go get gopkg.in/authboss.v1`?

2017-04-05 07:19 UTC, cuongquay approved these changes

2017-04-24 01:59 UTC, aarondl commented
Hey there. Apologies for lateness, this project's been at the very bottom of the priority list (with Authboss just above it I'm afraid :( )

Can we get a file extension for `env_sample` as it's clearly a shell script.

Also I believe @cintosyntax is correcti n that the go get (until 2.0) should be `go get gopkg.in/authboss.v1`

2017-04-24 12:05 UTC, closed without merging

2017-04-24 12:10 UTC, manhg commented
Thanks for feedback.
Sorry I made an mistake caused it closed. I opened another with fixes here https://github.com/go-authboss/authboss-sample/pull/15